services:

  backend:
    labels:
      org.springframework.boot.ignore: "true" # added for local dev - turn off for prod
    build:
      context: ./flexbox-backend
      dockerfile: Dockerfile
    container_name: flexbox-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://app-db:5432/${APP_DB}
      SPRING_DATASOURCE_USERNAME: ${DB_APP_ROLE}
      SPRING_DATASOURCE_PASSWORD: ${DB_APP_PASSWORD}
      # Migration user for Flyway
      DB_MIGRATION_ROLE: ${DB_MIGRATION_ROLE}
      MIGRATION_DB_PASSWORD: ${MIGRATION_DB_PASSWORD}
    depends_on:
      app-db:
        condition: service_healthy # wait for PostgreSQL health check to pass

  app-db:
    image: postgres:18
    container_name: flexbox-app-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${APP_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Halifax
    ports:
      # If APP_DB_PORT_HOST is not set it defaults to 5432
      - "${APP_DB_PORT_HOST:-5432}:5432"
    volumes:
      - app-postgres-data:/var/lib/postgresql/18/docker
      # Run scripts when the container starts for the first time
      - ./database/app-init:/docker-entrypoint-initdb.d
    # Make sure Spring Boot waits until PostgreSQL is ready
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${APP_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sandbox-db:
    image: postgres:18
    container_name: flexbox-sandbox-db
    restart: unless-stopped
    # Do not auto-config this container
    labels:
      org.springframework.boot.ignore: "true"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SANDBOX_DB}
      POSTGRES_USER: ${POSTGRES_SANDBOX}
      POSTGRES_PASSWORD: ${SANDBOX_PASSWORD}
      TZ: America/Halifax
    ports:
      # If SB_DB_PORT_HOST is not set it defaults to 5433
      - "${SB_DB_PORT_HOST:-5433}:5432"
    volumes:
      - sandbox-postgres-data:/var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_SANDBOX} -d ${SANDBOX_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app-postgres-data:
  sandbox-postgres-data: