openapi: "3.1.0"
info:
  title: Product Catalog API
  description: Flexbox Ecommerce Product Catalog API
  version: "1.0.0"
servers:
  - url: "https://flexbox_ecommerce"
paths:
  /subscription-boxes:
    get:
      summary: "GET subscription-boxes"
      operationId: "getAllSubscriptionBoxes"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SubscriptionBoxListResponse"
  /subscription-boxes/{id}:
    get:
      summary: "GET subscription-boxes/{id}"
      operationId: "getSubscriptionBoxById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SubscriptionBoxDetail"
  /products:
    get:
      summary: "GET products"
      operationId: "getAllProducts"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductListResponse"
  /products/{id}:
    get:
      summary: "GET products/{id}"
      operationId: "getProductById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductDetail"
components:
  schemas:
    BigDecimal:
      type: "object"
      properties: { }
    SubscriptionBoxPriceSummary:
      type: "object"
      properties:
        amount:
          nullable: true
          $ref: "#/components/schemas/BigDecimal"
        currency:
          type: "string"
          nullable: true
    SubscriptionBoxSummary:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        name:
          type: "string"
          nullable: true
        price:
          nullable: true
          $ref: "#/components/schemas/SubscriptionBoxPriceSummary"
    SubscriptionBoxListResponse:
      type: "object"
      properties:
        data:
          type: "array"
          nullable: true
          items:
            $ref: "#/components/schemas/SubscriptionBoxSummary"
    SubscriptionBoxProductSummary:
      type: "object"
      properties:
        productId:
          type: "integer"
          format: "int64"
          nullable: true
        productName:
          type: "string"
          nullable: true
        brand:
          type: "string"
          nullable: true
        quantity:
          type: "integer"
          format: "int32"
          nullable: true
    SubscriptionBoxDetail:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        name:
          type: "string"
          nullable: true
        description:
          type: "string"
          nullable: true
        price:
          nullable: true
          $ref: "#/components/schemas/SubscriptionBoxPriceSummary"
        products:
          type: "array"
          nullable: true
          items:
            $ref: "#/components/schemas/SubscriptionBoxProductSummary"
    CategorySummary:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        name:
          type: "string"
          nullable: true
    ProductSummary:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        category:
          nullable: true
          $ref: "#/components/schemas/CategorySummary"
        name:
          type: "string"
          nullable: true
        description:
          type: "string"
          nullable: true
        brand:
          type: "string"
          nullable: true
    ProductListResponse:
      type: "object"
      properties:
        data:
          type: "array"
          nullable: true
          items:
            $ref: "#/components/schemas/ProductSummary"
    ProductDetail:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        name:
          type: "string"
          nullable: true
        brand:
          type: "string"
          nullable: true
        description:
          type: "string"
          nullable: true
        category:
          nullable: true
          $ref: "#/components/schemas/CategorySummary"
        isActive:
          type: "boolean"
          nullable: true