CREATE
SEQUENCE IF NOT EXISTS address_address_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS cart_cart_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS cart_item_cart_item_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS category_category_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS checkout_session_checkout_session_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS invoice_invoice_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS marketing_consent_consent_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS newsletter_newsletter_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS order_item_order_item_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS order_order_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS payment_method_payment_method_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS payment_payment_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS product_inventory_product_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS product_product_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS role_role_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS subscription_box_price_subscription_box_price_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS subscription_box_subscription_box_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS subscription_plan_subscription_plan_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS tokens_token_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS user_user_id_seq START
WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS webhook_event_stripe_webhook_event_id_seq START
WITH 1 INCREMENT BY 1;

CREATE TABLE address
(
    address_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                  NOT NULL,
    unit_no       VARCHAR,
    civic_no      VARCHAR,
    street        TEXT,
    po_box_number TEXT,
    city          TEXT                    NOT NULL,
    province PROVINCES NOT NULL,
    postal_code   VARCHAR(7)              NOT NULL,
    country       VARCHAR(2) DEFAULT 'CA' NOT NULL,
    is_default    BOOLEAN    DEFAULT TRUE NOT NULL,
    is_active     BOOLEAN    DEFAULT TRUE NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    type ADDRESS_TYPE NOT NULL,
    CONSTRAINT address_pkey PRIMARY KEY (address_id)
);

CREATE TABLE cart
(
    cart_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    status CART_STATUS NOT NULL,
    CONSTRAINT cart_pkey PRIMARY KEY (cart_id)
);

CREATE TABLE cart_item
(
    cart_item_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id             BIGINT        NOT NULL,
    subscription_box_id BIGINT        NOT NULL,
    quantity            INTEGER       NOT NULL,
    unit_price_snapshot numeric(5, 2) NOT NULL,
    added_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT cart_item_pkey PRIMARY KEY (cart_item_id)
);

CREATE TABLE category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT NOT NULL,
    description TEXT,
    CONSTRAINT category_pkey PRIMARY KEY (category_id)
);

CREATE TABLE checkout_session
(
    checkout_session_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id              BIGINT                   NOT NULL,
    stripe_session_id    TEXT,
    subscription_plan_id BIGINT                   NOT NULL,
    payment_id           BIGINT,
    amount_subtotal      numeric(7, 2),
    amount_tax           numeric(7, 2),
    amount_total         numeric(7, 2),
    currency             VARCHAR(3) DEFAULT 'CAD' NOT NULL,
    success_url          TEXT,
    cancel_url           TEXT,
    expires_at           TIMESTAMP WITHOUT TIME ZONE,
    completed_at         TIMESTAMP WITHOUT TIME ZONE,
    created_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    mode CHECKOUT_SESSION_MODE NOT NULL,
    status CHECKOUT_SESSION_STATUS NOT NULL,
    CONSTRAINT checkout_session_pkey PRIMARY KEY (checkout_session_id)
);

CREATE TABLE invoice
(
    invoice_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stripe_invoice_id    TEXT,
    subscription_plan_id BIGINT        NOT NULL,
    amount_due           numeric(7, 2) NOT NULL,
    currency             VARCHAR(3) DEFAULT 'CAD',
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    paid_at              TIMESTAMP WITHOUT TIME ZONE,
    status INVOICE_STATUS NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT invoice_pkey PRIMARY KEY (invoice_id)
);

CREATE TABLE marketing_consent
(
    consent_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    action MARKETING_CONSENT_ACTION NOT NULL,
    CONSTRAINT marketing_consent_pkey PRIMARY KEY (consent_id)
);

CREATE TABLE newsletter
(
    newsletter_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          TEXT,
    subject       TEXT,
    html_file     TEXT,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    type NEWSLETTER_TYPE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT newsletter_pkey PRIMARY KEY (newsletter_id)
);

CREATE TABLE newsletter_subscribers
(
    newsletter_id BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    sent_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (newsletter_id, user_id)
);

CREATE TABLE "order"
(
    order_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                   NOT NULL,
    shipping_address_id BIGINT                   NOT NULL,
    billing_address_id  BIGINT                   NOT NULL,
    currency            VARCHAR(3) DEFAULT 'CAD' NOT NULL,
    total_amount        numeric(7, 2)            NOT NULL,
    order_date          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()     NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE                   NOT NULL,
    status ORDER_STATUS DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT order_pkey PRIMARY KEY (order_id)
);

CREATE TABLE order_item
(
    order_item_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id                       BIGINT        NOT NULL,
    subscription_box_id            BIGINT        NOT NULL,
    subscription_box_name_snapshot TEXT          NOT NULL,
    quantity                       INTEGER       NOT NULL,
    purchase_price_snapshot        numeric(5, 2) NOT NULL,
    CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE payment
(
    payment_id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id                 BIGINT                   NOT NULL,
    stripe_payment_intent_id TEXT,
    idempotency_key          CHAR(36),
    amount                   numeric(7, 2)            NOT NULL,
    currency                 VARCHAR(3) DEFAULT 'CAD' NOT NULL,
    paid_at                  TIMESTAMP WITHOUT TIME ZONE,
    status PAYMENT_STATUS NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT payment_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE payment_method
(
    payment_method_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                  BIGINT               NOT NULL,
    stripe_payment_method_id TEXT                 NOT NULL,
    last_4_digits            VARCHAR(4),
    expiration_month         INTEGER,
    expiration_year          INTEGER,
    is_default               BOOLEAN DEFAULT TRUE NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    type PAYMENT_METHOD_TYPE NOT NULL,
    CONSTRAINT payment_method_pkey PRIMARY KEY (payment_method_id)
);

CREATE TABLE product
(
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id   BIGINT               NOT NULL,
    sku           TEXT                 NOT NULL,
    brand         TEXT,
    name          TEXT                 NOT NULL,
    description   TEXT,
    cost_per_unit numeric(5, 2)        NOT NULL,
    is_active     BOOLEAN DEFAULT TRUE NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (product_id)
);

CREATE TABLE product_inventory
(
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    in_stock     INTEGER           NOT NULL,
    reserved     INTEGER DEFAULT 0 NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    product_id   BIGINT            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT product_inventory_pkey PRIMARY KEY (inventory_id)
);

CREATE TABLE role
(
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name ROLE_NAME NOT NULL,
    description TEXT,
    CONSTRAINT role_pkey PRIMARY KEY (role_id)
);

CREATE TABLE subscription_box
(
    subscription_box_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                TEXT                 NOT NULL,
    description         TEXT,
    image_file          TEXT,
    available_units     INTEGER              NOT NULL,
    is_active           BOOLEAN DEFAULT TRUE NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT subscription_box_pkey PRIMARY KEY (subscription_box_id)
);

CREATE TABLE subscription_box_price
(
    subscription_box_price_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subscription_box_id       BIGINT                   NOT NULL,
    amount                    numeric(5, 2)            NOT NULL,
    currency                  VARCHAR(3) DEFAULT 'CAD' NOT NULL,
    starts_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ends_at                   TIMESTAMP WITHOUT TIME ZONE,
    stripe_price_id           TEXT,
    CONSTRAINT subscription_box_price_pkey PRIMARY KEY (subscription_box_price_id)
);

CREATE TABLE subscription_box_product
(
    subscription_box_id BIGINT            NOT NULL,
    product_id          BIGINT            NOT NULL,
    quantity            INTEGER DEFAULT 1 NOT NULL,
    CONSTRAINT subscription_box_product_pkey PRIMARY KEY (subscription_box_id, product_id)
);

CREATE TABLE subscription_plan
(
    subscription_plan_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                BIGINT                NOT NULL,
    plan_name              TEXT                  NOT NULL,
    subscription_box_id    BIGINT                NOT NULL,
    shipping_address_id    BIGINT                NOT NULL,
    billing_address_id     BIGINT                NOT NULL,
    stripe_subscription_id TEXT,
    current_plan_start     TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    current_plan_end       TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    cancel_at_period_end   BOOLEAN DEFAULT FALSE NOT NULL,
    cancelled_at           TIMESTAMP WITHOUT TIME ZONE,
    created_at             TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    status SUBSCRIPTION_PLAN_STATUS NOT NULL,
    CONSTRAINT subscription_plan_pkey PRIMARY KEY (subscription_plan_id)
);

CREATE TABLE tokens
(
    token_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                NOT NULL,
    token_value TEXT                  NOT NULL,
    is_revoked  BOOLEAN DEFAULT FALSE NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    expired_at  TIMESTAMP WITHOUT TIME ZONE,
    type TOKEN_TYPE NOT NULL,
    CONSTRAINT tokens_pkey PRIMARY KEY (token_id)
);

CREATE TABLE "user"
(
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stripe_customer_id TEXT,
    email              TEXT                  NOT NULL,
    password_hash      TEXT                  NOT NULL,
    first_name         TEXT                  NOT NULL,
    last_name          TEXT                  NOT NULL,
    phone_number       VARCHAR(15)           NOT NULL,
    is_enabled         BOOLEAN DEFAULT FALSE NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (user_id)
);

CREATE TABLE user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE webhook_event
(
    stripe_webhook_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stripe_event_id         TEXT                  NOT NULL,
    event_type              TEXT                  NOT NULL,
    payload JSONB NOT NULL,
    is_processed            BOOLEAN DEFAULT FALSE NOT NULL,
    received_at             TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    processed_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT webhook_event_pkey PRIMARY KEY (stripe_webhook_event_id)
);

ALTER TABLE category
    ADD CONSTRAINT category_name_key UNIQUE (name);

ALTER TABLE checkout_session
    ADD CONSTRAINT checkout_session_stripe_session_id_key UNIQUE (stripe_session_id);

ALTER TABLE payment
    ADD CONSTRAINT idempotency_key_key UNIQUE (idempotency_key);

ALTER TABLE invoice
    ADD CONSTRAINT invoice_stripe_invoice_id_key UNIQUE (stripe_invoice_id);

ALTER TABLE payment_method
    ADD CONSTRAINT payment_method_stripe_payment_method_id_key UNIQUE (stripe_payment_method_id);

ALTER TABLE payment
    ADD CONSTRAINT payment_stripe_payment_intent_id_key UNIQUE (stripe_payment_intent_id);

ALTER TABLE product_inventory
    ADD CONSTRAINT product_inventory_product_id_key UNIQUE (product_id);

ALTER TABLE product
    ADD CONSTRAINT product_sku_key UNIQUE (sku);

ALTER TABLE role
    ADD CONSTRAINT role_name_key UNIQUE (name);

ALTER TABLE subscription_box_price
    ADD CONSTRAINT subscription_box_price_stripe_price_id_key UNIQUE (stripe_price_id);

ALTER TABLE subscription_plan
    ADD CONSTRAINT subscription_plan_stripe_subscription_id_key UNIQUE (stripe_subscription_id);

ALTER TABLE tokens
    ADD CONSTRAINT tokens_token_value_key UNIQUE (token_value);

ALTER TABLE "user"
    ADD CONSTRAINT user_email_key UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT user_stripe_customer_id_key UNIQUE (stripe_customer_id);

ALTER TABLE webhook_event
    ADD CONSTRAINT webhook_event_stripe_event_id_key UNIQUE (stripe_event_id);

CREATE UNIQUE INDEX address_user_id_type_idx ON address (user_id, type);

ALTER TABLE address
    ADD CONSTRAINT address_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE cart_item
    ADD CONSTRAINT cart_item_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES cart (cart_id) ON DELETE NO ACTION;

ALTER TABLE cart_item
    ADD CONSTRAINT cart_item_subscription_box_id_fkey FOREIGN KEY (subscription_box_id) REFERENCES subscription_box (subscription_box_id) ON DELETE NO ACTION;

ALTER TABLE cart
    ADD CONSTRAINT cart_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE checkout_session
    ADD CONSTRAINT checkout_session_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payment (payment_id) ON DELETE NO ACTION;

ALTER TABLE checkout_session
    ADD CONSTRAINT checkout_session_subscription_plan_id_fkey FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (subscription_plan_id) ON DELETE NO ACTION;

ALTER TABLE checkout_session
    ADD CONSTRAINT checkout_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE invoice
    ADD CONSTRAINT invoice_subscription_plan_id_fkey FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (subscription_plan_id) ON DELETE NO ACTION;

ALTER TABLE marketing_consent
    ADD CONSTRAINT marketing_consent_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE newsletter_subscribers
    ADD CONSTRAINT newsletter_subscribers_newsletter_id_fkey FOREIGN KEY (newsletter_id) REFERENCES newsletter (newsletter_id) ON DELETE NO ACTION;

ALTER TABLE newsletter_subscribers
    ADD CONSTRAINT newsletter_subscribers_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE "order"
    ADD CONSTRAINT order_billing_address_id_fkey FOREIGN KEY (billing_address_id) REFERENCES address (address_id) ON DELETE NO ACTION;

ALTER TABLE order_item
    ADD CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES "order" (order_id) ON DELETE NO ACTION;

ALTER TABLE order_item
    ADD CONSTRAINT order_item_subscription_box_id_fkey FOREIGN KEY (subscription_box_id) REFERENCES subscription_box (subscription_box_id) ON DELETE NO ACTION;

ALTER TABLE "order"
    ADD CONSTRAINT order_shipping_address_id_fkey FOREIGN KEY (shipping_address_id) REFERENCES address (address_id) ON DELETE NO ACTION;

ALTER TABLE "order"
    ADD CONSTRAINT order_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE payment_method
    ADD CONSTRAINT payment_method_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE payment
    ADD CONSTRAINT payment_order_id_fkey FOREIGN KEY (order_id) REFERENCES "order" (order_id) ON DELETE NO ACTION;

ALTER TABLE product
    ADD CONSTRAINT product_category_id_fkey FOREIGN KEY (category_id) REFERENCES category (category_id) ON DELETE NO ACTION;

CREATE INDEX idx_product_category_id ON product (category_id);

ALTER TABLE product_inventory
    ADD CONSTRAINT product_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE NO ACTION;

ALTER TABLE subscription_box_price
    ADD CONSTRAINT subscription_box_price_subscription_box_id_fkey FOREIGN KEY (subscription_box_id) REFERENCES subscription_box (subscription_box_id) ON DELETE NO ACTION;

ALTER TABLE subscription_box_product
    ADD CONSTRAINT subscription_box_product_product_id_fkey FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE NO ACTION;

ALTER TABLE subscription_box_product
    ADD CONSTRAINT subscription_box_product_subscription_box_id_fkey FOREIGN KEY (subscription_box_id) REFERENCES subscription_box (subscription_box_id) ON DELETE NO ACTION;

ALTER TABLE subscription_plan
    ADD CONSTRAINT subscription_plan_billing_address_id_fkey FOREIGN KEY (billing_address_id) REFERENCES address (address_id) ON DELETE NO ACTION;

ALTER TABLE subscription_plan
    ADD CONSTRAINT subscription_plan_shipping_address_id_fkey FOREIGN KEY (shipping_address_id) REFERENCES address (address_id) ON DELETE NO ACTION;

ALTER TABLE subscription_plan
    ADD CONSTRAINT subscription_plan_subscription_box_id_fkey FOREIGN KEY (subscription_box_id) REFERENCES subscription_box (subscription_box_id) ON DELETE NO ACTION;

ALTER TABLE subscription_plan
    ADD CONSTRAINT subscription_plan_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE tokens
    ADD CONSTRAINT tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;

ALTER TABLE user_role
    ADD CONSTRAINT user_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES role (role_id) ON DELETE NO ACTION;

ALTER TABLE user_role
    ADD CONSTRAINT user_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE NO ACTION;