spring.application.name=flexbox-backend
spring.datasource.url=jdbc:postgresql://localhost:5434/flexbox
spring.datasource.username=${DB_MIGRATION_ROLE}
spring.datasource.password=${MIGRATION_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration