spring.application.name=flexbox-backend

# Docker
spring.docker.compose.enabled=false

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Migration Datasource
spring.flyway.enabled=true
spring.flyway.user=${DB_MIGRATION_ROLE}
spring.flyway.password=${MIGRATION_DB_PASSWORD}
spring.flyway.locations=classpath:db/migration

# App Datasource
spring.datasource.url=jdbc:postgresql://localhost:5434/flexbox
spring.datasource.username=${DB_APP_ROLE}
spring.datasource.password=${DB_APP_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



