spring.application.name=flexbox-backend

# Docker
spring.docker.compose.enabled=true

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Migration Datasource
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://app-db:5432/flexbox
spring.flyway.user=${DB_MIGRATION_ROLE}
spring.flyway.password=${MIGRATION_DB_PASSWORD}
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# App Datasource
# Local
# spring.datasource.url=jdbc:postgresql://localhost:5434/flexbox
# Docker
spring.datasource.url=jdbc:postgresql://app-db:5432/flexbox
spring.datasource.username=${DB_APP_ROLE}
spring.datasource.password=${DB_APP_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



